### ISSUE TITLE
Use Cookies/persist with this lib

### ISSUE THREAD

**Issue by ivanjeremic** [brrd/electron-tabs#101]
Usually, when I use webview I can add a persist cookie has this tab lib an API to handle cookies? I would love to help id there is no easy way but for now, I was not able to find a solution.

**Comment by brrd** [comment]
There is no need for a specific API, you can already set webview tag's attributes with the `webviewAttributes` option and access the underlying webview with [`tab.webview`](https://github.com/brrd/electron-tabs#access-webview-element). Then you can use the usual Electron API.
