### ISSUE TITLE
Is it possible to place the tab bar as a sidebar?

### ISSUE THREAD

**Issue by kakyoism** [brrd/electron-tabs#102]
That's to say, I'll treat tabs as menu items. Then similar to most macOS apps' layout, say, Photos and Notes, I'd make the tab bar as the left sidebar of my app.

Is it easy to achieve?

**Comment by brrd** [comment]
> Is it easy to achieve?

Yes, if you know the basics about CSS. Simply remove the call to `electron-tabs.css` and write your own styles instead.

**Comment by kakyoism** [comment]
> > Is it easy to achieve?
> 
> Yes, if you know the basics about CSS. Simply remove the call to `electron-tabs.css` and write your own styles instead.

Well, would it be possible to reuse the existing .css?  I'm not exactly familiar with CSS and if you could give some pointers, such as which classes to change and what properties I could use, it would be highly appreciated.

**Comment by stuartambient** [comment]
> 
> 
> > > Is it easy to achieve?
> > 
> > 
> > Yes, if you know the basics about CSS. Simply remove the call to `electron-tabs.css` and write your own styles instead.
> 
> Well, would it be possible to reuse the existing .css? I'm not exactly familiar with CSS and if you could give some pointers, such as which classes to change and what properties I could use, it would be highly appreciated.

I wound up removed most of the classes.  etabs-tab and it's related classes (like hover) are the tabs themselves.  etabs-views and etab-view are related to the tab's webview.  

This is my html: 
`<div class="tabs" id="tabs">
        <div class="etabs-tabgroup">
          <div id="etabs-tabs" class="etabs-tabs"></div>
          <div class="etabs-buttons"></div>
        </div>
      </div>
      <div id="main" class="main">
        <div class="etabs-views"></div>
      </div>`

The tabs are separate but in the 'main div I put the webview in.
