### ISSUE TITLE
PDFs not opening in tab

### ISSUE THREAD

**Issue by ibnyusuf** [brrd/electron-tabs#104]
When attempting to open a PDF in a new tab, it does not work. Rather, I am prompted to save it to file. Below is the code for opening the link:

```
      let tab = tabGroup.addTab({
        src: url,
        visible: true,
        active: true,
        webviewAttributes: {
          'preload': path.join(__dirname, 'preload2.js'),
          plugins: true
        },
        ready: tab => {
          // Open dev tools for webview
          let webview = tab.webview;
          if (!!webview) {           
            webview.addEventListener('dom-ready', () => {
              webview.openDevTools();
              var t = webview.getTitle();
              if(t.indexOf(".") !== -1){
                tab.setTitle(t.substring(0, t.indexOf(".")));
              } else {
                tab.setTitle(t);                        
              }
            });
            webview.addEventListener('close', () => {
              mainTabWebview.send('refresh');
              tab.close()
            });                
          }
        }
      });
```
To my understanding, setting `plugins` to `true` should allow PDFs to open, but this does not appear to be the case? Below is a screenshot of what I see:

![saving_pdf](https://user-images.githubusercontent.com/32095361/79781059-d6974f80-8334-11ea-8da1-8e9b04c6b43a.jpg)

I am not sure whether this is an electron tabs issue or not. If not, please feel free to close it. Thanks

**Comment by brrd** [comment]
This is not related to electron-tabs. You need to use a PDF viewer in your application to display PDF. Most browsers use PDF.js: https://github.com/mozilla/pdf.js
Someone created an example featuring Electron and PDF.js here: https://github.com/seanchas116/electron-pdfjs
