### ISSUE TITLE
Electron tabs does not work  with Electron V5.0.0 and up 

### ISSUE THREAD

**Issue by purencool** [brrd/electron-tabs#105]
**Describe the bug**
electron-tabs does not work on any version of Electron from 5.0.0 it throws the following error

Console error when you use 5.0.0 versions and up of electron

`Uncaught ReferenceError: require is not defined
    at main.js:1
/Users/john.cullen/D…ity-warnings.js:170 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.
 
For more information and help, consult
HTTP s://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.`

File error

`
const TabGroup = require('electron-tabs');
`

**To Reproduce**
`
{
  "name": "electron-tabs",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "bootstrap": "^4.4.1",
    "electron": "^5.0.0", <--- This version does not work
    "electron-tabs": "^0.15.0"
  }
}
`

`
{
  "name": "electron-tabs",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "bootstrap": "^4.4.1",
    "electron": "^4.2.12", <---- This does work
    "electron-tabs": "^0.15.0"
  },
`

**Expected behavior**
Electron should load and display tabs

**Please complete the following information**
 - OS: Mac
 - electron-tabs version look above
 - Electron version  look above

**Code**
See JSON above 

**Screenshots**
N/A

**Additional information**
N/A

**Comment by brrd** [comment]
Electron-tabs demo [uses Electron 8](https://github.com/brrd/electron-tabs/blob/38444e6641c41ecc34cd2dbc5a0114efeeec2748/package.json#L23) without any problem (at least until now).

Can you please try the following steps:

1. Make a new clone of electron-tabs 
2. Open terminal in its directory
3. `npm install`
4. `npm run demo`
5. Tell us what happens

**Comment by purencool** [comment]
Sure I will do it next weekend

**Comment by rafaelcn** [comment]
Working here with electron 9.0

**Comment by brrd** [comment]
I'm closing this issue until we get more information.
