### ISSUE TITLE
Anchor link with target blank won't open

### ISSUE THREAD

**Issue by rafaelcn** [brrd/electron-tabs#106]
Every link with a target _blank won't open in a new tab. I know this might not be your responsibility to handle and I'd like to know how to go around that. Is this a limitation of the `web view` component? Can I listen to click events on anchor links and simply add a new tab with the `href` of that anchor link?

**Comment by rafaelcn** [comment]
This is more of a question than a bug report, so that's why I chose this format.

**Comment by brrd** [comment]
I would listen to webview events such as ["will-navigate"](https://www.electronjs.org/docs/api/webview-tag#event-will-navigate) or ["new-window"](https://www.electronjs.org/docs/api/webview-tag#event-new-window) (I don't know which one is appropriate, you will need to try):

```js
tab.webview.addEventListener('new-window', (e) => {
  tabGroup.addTab({src: e.url});
});
```

This is just an idea, you will have to adapt it to your needs.

**Comment by rafaelcn** [comment]
Thank you, I'm not a front web developer and I might come back for more 😆. Thank you for this wonderful implementation of tabs, I have tried a lot of things and your implementation serves me well.
