### ISSUE TITLE
Webview not showing after Build Electron

### ISSUE THREAD

**Issue by HansLanger** [brrd/electron-tabs#109]
Hi, I'm able to make the demo work with "npm run demo", but when I use electron-packager to create an ".exe" it doesnt show the webview. It is loading the HTML file because I added a text and it is showing it, but it just doesnt show the tabs and webview. Any idea why?

I already tried:
`const mainWindow = new BrowserWindow({
    webPreferences: {
      nodeIntegration: true,
      nodeIntegrationInWorker: true,
      webviewTag: true,
      allowRunningInsecureContent:true
    }
  });`

**Comment by brrd** [comment]
Any log in the terminal and/or console?
Can you provide a sample?

**Comment by HansLanger** [comment]
> Any log in the terminal and/or console?
> Can you provide a sample?

I though it was a security issue but it seems to be a path issue, i get this error on console:

`Uncaught Error: Cannot find module 'electron-tabs'`

In this line:
`const TabGroup = require('electron-tabs') //normally but for demo :
  // const TabGroup = require("../index");
`
Note that it works on "npm run demo"

**Comment by brrd** [comment]
Ok I understand. You are using electron-packager directly on the `demo/` directory.
Try to run `npm install -s electron-tabs` from the `demo/` directory , this may solve your issue. 
If not, then I think the most simple way would be to create a clean electron project and install electron-tabs as a dependency (which is actually the correct way to do).

**Comment by HansLanger** [comment]
Ok, fixed:
The electron packager was not including the index.js file that includes the "Tab classes", I moved the file into the src folder and recompiled and now is working, 
Thanks!
