### ISSUE TITLE
Ability to activate new tab from inside a tab window

### ISSUE THREAD

**Issue by coreybruce** [brrd/electron-tabs#111]
Hi I want to make a button inside the tabbed webpage that will open a new tab to a specific page, is this possible? 

It would be awesome if I can have the browser standard of target="_blank to open a new tab :)

**Comment by brrd** [comment]
You have to use IPC messages to communicate between processes. See: https://www.electronjs.org/docs/api/webview-tag#event-ipc-message

Example (not tested):

```javascript
// In browser process:
const { ipcRenderer, shell } = require("electron");
tab.webview.addEventListener("ipc-message", (event) => {
	const { channel, args } = event;
	if (channel === "openURL") {
		const url = args[0];
		let tab = tabGroup.addTab({
			src: url,
			visible: true
		});
	}
});

// In tab process preload script:
window.openURL = (url) => {
	ipcRenderer.sendToHost("openURL", url);
};

// Then use it in tab process:
openURL("https://github.com");
```

> It would be awesome if I can have the browser standard of target="_blank to open a new tab :)

Creating a browser API is out of the purpose of electron-tabs. You will have to implement this features by your own (which should be quite simple by mixing the previous example with a "click" event listener on `a[target="_blank"]` elements).

**Comment by coreybruce** [comment]
Okay I will give it a try
