### ISSUE TITLE
How to create shortcuts for electron tabs? 

### ISSUE THREAD

**Issue by MY020452** [brrd/electron-tabs#112]
I have created set of tabs with predefined urls. 

Eg:  Tab1 -> www.google.com
       Tab2 - > www.news.com
        Tab3 - > www.greetings.com

Please advance to create shortcut for each tabs.

**Comment by MY020452** [comment]
> I have created set of tabs with predefined urls.
> 
> Eg: Tab1 -> [www.google.com](http://www.google.com)
> Tab2 - > [www.news.com](http://www.news.com)
> Tab3 - > [www.greetings.com](http://www.greetings.com)
> 
> Please advance to create shortcut for each tabs.

**Comment by brrd** [comment]
Please first read the documentation where you will find everything you need to know about electron-tabs: https://github.com/brrd/electron-tabs/blob/master/README.md

If you have a specific question after this, then fell free to open a new issue with a detailed description.
