### ISSUE TITLE
How do I add the new tab button

### ISSUE THREAD

**Issue by CleverCarpet** [brrd/electron-tabs#114]
I need help adding the new tab button

**Comment by CleverCarpet** [comment]
![image](https://user-images.githubusercontent.com/72514113/103712342-d00a4000-4f76-11eb-9683-d69c3a621834.png)

**Comment by brrd** [comment]
Simply define the [`newTab` option](https://github.com/brrd/electron-tabs#new-tabgroupoptions). Its value will be passed to [`addTab()`](https://github.com/brrd/electron-tabs#tabgroupaddtaboptions) when the button is clicked.

```js
const tabGroup = new TabGroup({
    newTab: {
        title: "New Tab",
        src: "https://github.com"
        active: true
    }
});
```
