### ISSUE TITLE
Replace `ready` callbacks by Promises

### ISSUE THREAD

**Issue by brrd** [brrd/electron-tabs#117]

**Comment by nitishdhar** [comment]
Is this what's going to help with a use case where we need to do something in the main process once tabGroup is ready? e.g. right now if we need to initialize a new tab from the main process after app ready, is there a way to register that tab request and wait for tabGroup to be ready and then initialize the tab?

I am aware you don't have a lot of time to work on this project, either way, thanks for working on this, it's been really helpful.

thanks

**Comment by brrd** [comment]
> Is this what's going to help with a use case where we need to do something in the main process once tabGroup is ready? 

Nope. This is just a change in the API, but the features will remain exactly the same.

> e.g. right now if we need to initialize a new tab from the main process after app ready, is there a way to register that tab request and wait for tabGroup to be ready and then initialize the tab?

IMO this issue is not specific to electron-tabs, it depends most widely on the way you design your application. I can't answer your question with so little information (and anyway this is not the purpose of this project to help developers designing their application) but I would advice you to have a look to [IPC main](https://www.electronjs.org/docs/api/ipc-main) and [IPC renderer](https://www.electronjs.org/docs/api/ipc-renderer) modules, which will help you to communicate between main and renderer processes. In renderer process you can listen for IPC messages in order to 1) if `tabGroup` is ready, directly create tab 2) otherwise push the request in a `queue` array, which will be processed in electron-tabs `ready` callback once `tabGroup` is ready.
