### ISSUE TITLE
[enhancement] Use chrome style tabs

### ISSUE THREAD

**Issue by Bellisario** [brrd/electron-tabs#118]
I've found [this project](https://github.com/adamschwartz/chrome-tabs) with a very beautiful style. If the current style it's too liked, you can also add this style with user style choose (ex. "default" and "chrome like").

**Comment by brrd** [comment]
Yes. I used to contribute to this project to make it usable as a dependency, with the idea that electron-tabs could depend on it. Then I lacked time to go on. 

It is beautiful, but it lacks a lot of features compared to the current electron-tabs API. It is still in my plan to at least get inspired by it when working on the next redesign.

**Comment by ShlomiRex** [comment]
Like this?
https://github.com/ShlomiRex/electron-browser

**Comment by Bellisario** [comment]
Yes!

**Comment by brrd** [comment]
Electron-tabs got new styles in version 1.0.0, and you can easily define your own styles: https://github.com/brrd/electron-tabs#custom-styles
