### ISSUE TITLE
Integration testing of electron-tabs

### ISSUE THREAD

**Issue by coda-nsit** [brrd/electron-tabs#123]
I want to have integration tests for the tabs. Concretely speaking I want the ability to,
1. Click on the + sign to open new tab.
2. Click on the x sign to close a tab.
3. My electron application has [electron global shortcuts](https://www.electronjs.org/docs/api/global-shortcut) for example, cmd+t opens a new tab, cmd+w closes a tab. 

I would want to simulate such behaviors in an automatic way.

**Comment by brrd** [comment]
Why not triggering mouse or key events in JavaScript?
