### ISSUE TITLE
how to use ready?

### ISSUE THREAD

**Issue by Ezrabro** [brrd/electron-tabs#127]
how to use ready?
**ready: a callback function to call once the tab is ready. The Tab instance is passed as the only parameter.**
idk how to use it
and is there ant thing like `tab.on("ready", (tab) => { ... });`
here is my code
```
const TabGroup = require("electron-tabs");

function tabReady() {
    let webview = tab.webview;
    webview.addEventListener('dom-ready', () => {
        webview.openDevTools();
    });
};

let tabGroup = new TabGroup({
  viewContainerSelector: ".webview",
  newTab: {
    title: "presearch",
    src: "https://presearch.org/",
    visible: true,
    active: true,
    ready : tabReady(),
    webviewAttributes: {
        preload : "instantpage.js"
    },
  },
});


tabGroup.addTab();
```

**Comment by brrd** [comment]
I see two problems in your code:

1) `tab` parameter is missing in the function:

```js
function tabReady(tab) {
```

2) The `ready` option's value is `undefined` here, because the `tabReady` function is executed. Instead you should just reference it:

```js
ready : tabReady,
```

**Comment by Ezrabro** [comment]
thanks
