### ISSUE TITLE
How to fix "TypeError: Cannot read property 'appendChild' of undefined" errors?

### ISSUE THREAD

**Issue by mwxdxx** [brrd/electron-tabs#131]
I was making a browser with Electron and electron-tabs, but I'm about to give up. Because I saw this error.

### Environments
Windows 11 Home Insider Dev Build 22499.1010
Node.js v14.17.0
Electon v13.1.7
electron-tabs v0.15.0

### Errors
VM75 renderer_init.js:93 Unable to load preload script: D:\Electron\Rubicone\src\preload.js
VM75 renderer_init.js:93 TypeError: Cannot read property 'appendChild' of undefined
    at VM89 D:\Electron\Rubicone\node_modules\electron-tabs\index.js:22
    at Object.<anonymous> (VM89 D:\Electron\Rubicone\node_modules\electron-tabs\index.js:23)
    at Object.<anonymous> (VM89 D:\Electron\Rubicone\node_modules\electron-tabs\index.js:459)
    at Module._compile (VM43 loader.js:1078)
    at Object.Module._extensions..js (VM43 loader.js:1108)
    at Module.load (VM43 loader.js:935)
    at Module._load (VM43 loader.js:776)
    at Function.f._load (VM70 asar_bundle.js:5)
    at Function.o._load (VM75 renderer_init.js:33)
    at Module.require (VM43 loader.js:959)

### Sources
main.js
```js
const {app,BrowserWindow} = require('electron');
const path = require('path');

function createWindow () {

    let win = new BrowserWindow({
        width: 1000,
        height: 800,
        webPreferences: {
            nodeIntegration: false,
            enableRemoteModule: true,
            contextIsolation: true,
            preload: path.join(__dirname, 'preload.js')
        },
    });
    win.loadFile("src/main.html");
}
app.whenReady().then(createWindow);
```
main.html
```html
<html>
    <head><title>Rubicone</title></head>
    <body>
      <div class="etabs-tabgroup">
        <div class="etabs-tabs"></div>
        <div class="etabs-buttons"></div>
      </div>
      <div class="etabs-views"></div>
      <link rel="stylesheet" href="../node_modules/electron-tabs/electron-tabs.css">
    </body>
</html>
```
preload.js
```js
const TabGroup = require("electron-tabs");
let tabGroup = new TabGroup();
let tab = tabGroup.addTab({
title: "New Tab",
src: "https://bing.com",
visible: true
});
```
[zip Archive of sources](https://drive.google.com/file/d/157WlX_kJaZOE8Nq7tTaVKS9HfV112P2x/view?usp=sharing)

note:Maybe I should have posted this Issue as a bug

**Comment by mwxdxx** [comment]
I could fix this, But webview doesn't work.

### How I fix this
fix preload.js like this:
```js
window.addEventListener('load', ()=>{
    const TabGroup = require("electron-tabs");
    let tabGroup = new TabGroup();
    let tab = tabGroup.addTab({
    title: "New Tab",
    src: "https://bing.com",
    visible: true
    });
});
```
Thanks TMP_tenpura!

**Comment by brrd** [comment]
> I could fix this, But webview doesn't work.

What do you mean?

**Comment by mwxdxx** [comment]
Sorry for late reply, like this.
![image](https://user-images.githubusercontent.com/43317582/147747512-f11203ae-e78c-470a-888d-f555a3554f19.png)
Console doesn't put some errors...(I wonder I entered bad url)

**Comment by brrd** [comment]
You must use the following options for webPreferences, as explained [in the documentation](https://github.com/brrd/electron-tabs#usage):

```js
  webPreferences: {
    nodeIntegration: true,
    webviewTag: true
  }
```

**Comment by mwxdxx** [comment]
I tought I set it true...but it was false, Thanks!
