### ISSUE TITLE
How to enable navigation and input for navigation?

### ISSUE THREAD

**Issue by marcelodelta** [brrd/electron-tabs#133]
How to enable navigation and input for navigation?

Similar to the image below

https://user-images.githubusercontent.com/29538843/29670982-9cf563c8-88e8-11e7-9a81-f608bb443733.PNG

**Comment by brrd** [comment]
Electron-tabs is only intended to create tabs. If your question is about how to make a full browser UI then I'm sorry but it is definitely out of the scope of this project. You will find everything you need in [Electron documentation](https://www.electronjs.org/).
