### ISSUE TITLE
new TabGroup() catch error

### ISSUE THREAD

**Issue by JosephusZhou** [brrd/electron-tabs#14]
the html:
![image](https://cloud.githubusercontent.com/assets/5844075/24139565/83c12538-0e57-11e7-8103-f18067ad4184.png)

the js:
![image](https://cloud.githubusercontent.com/assets/5844075/24139559/7d8941dc-0e57-11e7-9065-114724758017.png)

the error:
![image](https://cloud.githubusercontent.com/assets/5844075/24139589/97ee2402-0e57-11e7-9dcc-2cfd4b6fe79e.png)

**Comment by brrd** [comment]
Try: `const TabGroup = require("electron-tabs");` (without the `{ }` around `TabGroup`)

**Comment by brrd** [comment]
I'm closing this issue, assuming this problem is solved.
