### ISSUE TITLE
donot   fire   javascript

### ISSUE THREAD

**Issue by samantrader** [brrd/electron-tabs#159]
hi    

i  create   an electron  application  with  two  tabs  that   use  local  html  file   

but   when  run  application      active  tab   page   donot   trigger      javascript of  active page    

why  ?

**Comment by brrd** [comment]
Please provide a code sample. Otherwise there is no way to answer your question.

**Comment by samantrader** [comment]
my   electrontab.html  is:
 `

<!DOCTYPE html>
<html>
<head>
  <title>electron-tabs-demo</title>
</head>
<body style="margin:0">
<tab-group new-tab-button="true" sortable="true">
  <style>
    /* Add custom styles */
    .my-badge {
      background-color: #327BB1;
    }
    .my-custom-tab {
      color: #d135d1;
      font-style: italic;
      font-weight: bold;
    }
  </style>
</tab-group>
<script src="./electron-tabs.js"></script>
<script>
  const tabGroup = document.querySelector("tab-group");
  tabGroup.on("ready", () => console.info("TabGroup is ready"));
 let r= tabGroup.addTab({
    title: "my title",
    src: "index.html",
    badge: {
      text: "5",
      classname: "my-badge"
    },
    active: true
  });

  tabGroup.addTab({
    title: "electron-tabs on Github",
    src: "https://github.com/",
  
  });
  r.activate()
</script>
</body>
</html>

and    index.js  that  is  script of  index.html  is   :


const ipcRenderer = require('electron').ipcRenderer;
const electron = require("electron")
 const { BrowserWindow } = require('@electron/remote')
const {dialog} = require('@electron/remote')

    window.onload = function () {
 
     let  t=localStorage.getItem("id");
}


`
that   windows.onload  donot  fire

**Comment by brrd** [comment]
Actually your question is related to electron webview tag, not to electron-tabs itself. Please read the [related documentation](https://www.electronjs.org/docs/latest/api/webview-tag) or ask the Electron community.
