### ISSUE TITLE
window.require is not a function

### ISSUE THREAD

**Issue by DONGNEZHA** [brrd/electron-tabs#160]
According to the official electron documentation for the webview property,
[https://www.electronjs.org/docs/latest/api/webview-tag](url)
I set 
`        tabGroup.addTab({
        title: "My Custom Tab",
        src: "http://localhost:8000",
        webviewAttributes: { nodeintegration: true },
      });`
but the guest page in webview still report "Uncaught (in promise) TypeError: window.require is not a function" when i require 'electron'.
`window.require('electron').ipcRenderer`
Incidentally, the link to the documentation ("webview documentation") in the explanation of the webviewAttributes parameter in the readme seems to have failed.

**Comment by brrd** [comment]
@DONGNEZHA Can you provide sample code in a dedicated repo please?

**Comment by Benedict-Kpaduwa** [comment]
For window.require to work, you will need to setup your web preferences like this
webPreferences:{
   nodeIntegration: true,
   contextIsolation: false,
   enableRemoteModule: true
}
