### ISSUE TITLE
how to open a new tab from other tab page?

### ISSUE THREAD

**Issue by lanix516** [brrd/electron-tabs#162]
tabGroup.on("ready", () => console.info("TabGroup is ready"));

let tab = tabGroup.addTab({
    title:"index",
    src:"index.html",
    active: true,
  })

here is other page named second.html,  now i need to open it in a new tab by click a button in index.html,
i have tried webiew object ,  postmessage, ipcRenderer ,no one really worked.

**Comment by lanix516** [comment]
`let tab = tabGroup.addTab({
    title:"首页",
    src:"index.html",
    active: true,
    webviewAttributes:{
      preload:"./preload-tab.js"
    }
  })`
that worked!  a message  send like this
index.html (preload-tab.js)=>main.js=>electron-tab.html(preload.js)=>electron-tab.html 


how can i send msg from index.html to electron-tab.html directly?

**Comment by brrd** [comment]
Everything is explained here: https://www.electronjs.org/docs/latest/tutorial/ipc
