### ISSUE TITLE
hotkeys stop working

### ISSUE THREAD

**Issue by hz2018tv** [brrd/electron-tabs#167]
most default hotkeys stop working after electron-tabs is activated, like Ctrl+Q for "Quit" (clicking on Quit still works), so far, only Ctrl+R and Ctrl+Shift+R are working. thanks!

**Comment by brrd** [comment]
Electron-tabs doesn't deal with hotkeys. This is  obviously related to your Electron app, not to electron-tabs. Please open an issue in Electron issue tracker.
