### ISSUE TITLE
tab header row

### ISSUE THREAD

**Issue by hz2018tv** [brrd/electron-tabs#169]
is there a way to cutoff the shaded area of the tab header row to be right after the last tab? see picture please. thanks
![screen](https://user-images.githubusercontent.com/44717154/201394622-ba6e49bf-53c8-4db8-89cd-5d59b92bc51c.png)

**Comment by brrd** [comment]
I can't reproduce. Please give sample code.

**Comment by brrd** [comment]
See https://github.com/brrd/electron-tabs/issues/170#issuecomment-1316586195
