### ISSUE TITLE
Allow user to rename tabs

### ISSUE THREAD

**Issue by tennis-aa** [brrd/electron-tabs#178]
**Is your feature request related to a problem? Please describe.**
I would like to provide the user an option to rename tabs. I found a way that is simple enough but may be accessing some private elements of the module.

**Describe the solution you'd like**
I can rename tabs with the following:
```html
<tab-group new-tab-button="true" sortable="true"></tab-group>

<script src="node_modules/electron-tabs/dist/electron-tabs.js"></script>

<script>
  // Select tab-group
  const tabGroup = document.querySelector("tab-group");

  // Setup the default tab which is created when the "New Tab" button is clicked
  tabGroup.setDefaultTab({
    title: "New Page",
    src: "https://www.example.com/",
    active: true,
    ready: tab_init
  });

  // Create a new tab by default
  tabGroup.addTab();

  // Some additional functionality for new tabs
  function tab_init(tab) {
    tab.setTitle("Page " + tabGroup.newTabId);
    let tab_title = tab.element.children[1];
    tab_title.addEventListener("click", function() {
      tab_title.setAttribute("contenteditable", true);
    });
    tab_title.addEventListener("blur", function() {
      tab_title.setAttribute("contenteditable", false);
      if (tab_title.textContent == "") tab_title.textContent = "No title";
      tab.setTitle(tab_title.textContent);
    });
  }
</script>
```
When I click twice on the title of the tab, it allows me to modify the title.

It works fine but my concern with this solution is that I am accessing and modifying `tab.element.children[1]` which is not part of the API and may run into issues later.

Is there a better way to achieve renamable tabs? Ideally, I would like to pass a `renamable="true"` attribute to the `<tab-group>` element.

**Additional context**
Here is a short video of the functionality I get with the html above.

https://user-images.githubusercontent.com/82269693/215623276-c6e000c5-cdd9-4b64-9cb0-c9f55f0c5119.mp4

**Comment by brrd** [comment]
We won't add this feature because I think this is out of the scope of electron-tabs, which is intended to be generic and KISS lib.

Why not accessing title element with `tab.spans.title`, as we do in : https://github.com/brrd/electron-tabs/blob/49525b8634e949f8875f47dd4700cfe0c94e41a3/src/index.ts#L415

By the way, be aware that `contenteditable` does not filter out HTML elements, so pasting a h1 in the tab would lead to a broken display. I guess you do want raw text, so you probably need to use `window.prompt` instead. Untested example:

```js
 function tab_init(tab) {
    const tabTitle = tab.spans.title;
    tab.setTitle("Page " + tabGroup.newTabId);
    tabTitle.addEventListener("click", function() {
        const newTitle = window.prompt("Please type the new title");
        tab.setTitle(newTitle);
    });
  }
```

**Comment by tennis-aa** [comment]
Thank you for the quick reply. `tab.spans.title` is exactly what I was looking for.

I have a few comments if anybody else is looking for this functionality. 

`window.prompt` is not supported by electron, so you would have to write your own prompt function (https://github.com/electron/electron/issues/472).

What I ended up using is the following:
```js
function tab_init(tab) {
  tab.setTitle("Page " + tabGroup.newTabId);
  let tab_title = tab.spans.title;
  tab.element.addEventListener("click", function() {
    tab_title.setAttribute("contenteditable", true);
  });
  tab_title.addEventListener("blur", function() {
    tab_title.setAttribute("contenteditable", false);
    if (tab_title.textContent == "") tab_title.textContent = "No title";
    tab_title.textContent = tab_title.textContent;
  });
}
```

`contenteditable` does not filter out pasted html elements, so I am filtering it out myself (`tab_title.textContent = tab_title.textContent;`).

I am not calling `tab.setTitle()` because it modifies the `innerHTML` of the title span so html code would be rendered.
