### ISSUE TITLE
electron-tabs will not load local (file://) URL no matter what content it is

### ISSUE THREAD

**Issue by kevingoss2** [brrd/electron-tabs#182]
Tab will not load if it is a local file.

main process
```
  let win = new BrowserWindow({
    width: isDev ? 2500 : 1700,
    height: 1200,
    show: false,
    webPreferences: {
      webviewTag: true,
      nodeIntegration: true,
      enableRemoteModule: true,
      contextIsolation: false,
      nodeIntegrationInWorker: true,
      nodeIntegrationInSubFrames: true,
      enableBlinkFeatures: "CSSColorSchemeUARendering",
      webSecurity: false,
      preload: __dirname + '/preload.js'
    },
    icon: image,
  });
  mainWindow = win;
  windows.push(win);
  win.on('closed', function(e){
    let counter = 0;
    windows.forEach((w,i) => {
      if(w === e.sender)
        counter = i
    })
    if(counter >= 0)
      windows.splice(counter, 1);
    updateWindowMenu()
  })
  win.maximize();
  win.loadURL(`file://${path.join(__dirname, '../build/test.html')}`).then((e) => {
  }).catch((e) => console.log(e.message));

  win.show();
```

Test.html
```
<html>
<head>
    <meta charset="utf-8">
    <title>electron-tabs</title>
    <link href="style.css" rel="stylesheet">
</head>
<body>
<tab-group new-tab-button="true"></tab-group>

<script src="electron-tabs.js"></script>

<script>
  // Select tab-group
  const tabGroup = document.querySelector("tab-group");

  // Setup the default tab which is created when the "New Tab" button is clicked
  tabGroup.setDefaultTab({
    title: "New Page",
    src: "index.html",
    active: true,
    webviewAttributes: {
      nodeIntegration: true,
    }
  });

  // Do stuff
  const tab = tabGroup.addTab({
    title: "electron-tabs on NPM",
    src: "https://www.npmjs.com/package/electron-tabs"
  });
  const pos = tab.getPosition();
  console.log("Tab position is " + pos);
</script>
</body>
</html>
```

**Expected behavior**
Tabs with local addresses (file://) should show up

 - macos
 - electron-tabs version 1.0.1
 - Electron version 20.1.3

**Screenshots**
<img width="1586" alt="image" src="https://user-images.githubusercontent.com/32524939/224580370-61be1062-f2f7-4a28-b402-9599a3bb7f14.png">

I have tried almost all webview options to make this work.  No matter what I do, on my main page or this test page I cannot get it to load local files.  I replaced the BrowserWindow url with the one I load in the tab, and it loads fine.  But as a tab, no local files will load.

**Comment by brrd** [comment]
Please give information about:

 - OS: [e.g. iOS]
 - electron-tabs version [e.g. 0.12.0]
 - Electron version [e.g. 8.0.0]

**Comment by kevingoss2** [comment]
I did:
macos (Monteray)
electron-tabs version 1.0.1
Electron version 20.1.3

**Comment by brrd** [comment]
Sorry, I didn't see it in the "Expected behavior" section.

Assuming every file is in the same directory, did you try  `src: "./index.html",` (with `./`)?

**Comment by kevingoss2** [comment]
Yeah I tried that.  It did not work.

**Comment by kevingoss2** [comment]
I created a new project with minimal code and it doesn't work either.  Relative or physical absolute paths

**Comment by kevingoss2** [comment]
The URL in the webview src is correct.  see screenshot above

**Comment by brrd** [comment]
> I created a new project with minimal code and it doesn't work either. Relative or physical absolute paths

Could you provide this projet URL please?

**Comment by kevingoss2** [comment]
https://github.com/kevingoss2/tabs-test
This is a minimal test.  It tries to load a test.html file (hello world) with no js.  Doesn't show up.

**Comment by kevingoss2** [comment]
It did work with the test sample.  The issue I am running into is that it will not load a react site.  The test "hello world" page loads fine.

**Comment by brrd** [comment]
Electron-tabs is intended to be used with vanilla JS only. You will have to adapt it by yourself or to find an alternative working with React. I'm sorry.

**Comment by kevingoss2** [comment]
I managed to figure it out.  One more question though... Can we assign ids to tabs?

**Comment by kevingoss2** [comment]
Thanks for a great library.  I would ask if you could add a feature for overflowing tabs and resizing tabs based on number and width.
