### ISSUE TITLE
setWindowOpenHandler not firing on the main process

### ISSUE THREAD

**Issue by cascopia** [brrd/electron-tabs#186]
mainWindow is a BrowserWindow
mainWindow.webContent loads 'main.html' renderer file, which contains 'electron-tabs (<tab-group>)' component inside.

When I click a link with target="_blank" inside the 'tab', nothing happens.

the webview inside the 'tab' also do not call any of 'did-start-loading', 'did-start-navigation', etc.

also, the following function is not called.

```
mainWindow.webContent.setWindowOpenHandler((handler) => {
        // NOT CALLED
        return {
          action: "allow"
        };
    });
```

Is there anything that I am missing?

**Comment by brrd** [comment]
Actually this question is not specific to electron-tabs. The way electron-tabs handles webviews is 100% standard, so you will probably find the required support in Electron documentation and community: https://www.electronjs.org/
