### ISSUE TITLE
A way to restore all tabs

### ISSUE THREAD

**Issue by djalmaaraujo** [brrd/electron-tabs#19]
Would be nice to have a way to restore all tabs if I close the app (cmd+Q) and open again.

**Comment by djalmaaraujo** [comment]
@brrd That is what I am going to do because restoring "Windows" is actually too generic. I agree with you in terms of the goal of your project. I just think that if we add this flexibility you suggested, would be great.

**Comment by brrd** [comment]
OK, so I created a new issue #20.
