### ISSUE TITLE
Error including electron-tabs to electron app

### ISSUE THREAD

**Issue by holuwaseun** [brrd/electron-tabs#21]
![electron-tabs error](https://cloud.githubusercontent.com/assets/5493426/25312038/68d62dd6-2806-11e7-9c8c-30e1a281d85e.JPG)
I get the following error when I tried
`
const TabGroup = require("electron-tabs");
`

**Comment by brrd** [comment]
You're obviously trying to call the module from the main process, which won't work. electron-tabs must be used **in the renderer process**. 
See [this documentation](http://electron.atom.io/docs/tutorial/quick-start/#renderer-process) and #3 for further information.
