### ISSUE TITLE
Adding tab at specified index 

### ISSUE THREAD

**Issue by Datta973** [brrd/electron-tabs#23]
I want it to be able to add a tab at specified index ...for example i created a "+" tab  and when i click it a new tab should be created before "+" tab ,not after "+" tab ..so how can i do it? is it possible to set index of a tab?

**Comment by brrd** [comment]
Currently there is no API to do this, but you can use the ready callback when creating the tab and reposition the tab element which is referenced in the `.tab` property.

I would say (not tested):

```javascript
tabGroup.addTab({
  title: "...",
  src: "...",
  visible: false,
  ready: function (tab) {
    const tabElement = tab.tab;
    // Then here move tabElement wherever you want...
    // (...)
    // ...and display the tab when it is done:
    tab.show();
  } 
});
```

BUT as I can guess be reading your example, it maybe looks like you are trying to mimic a new tab button which is normally natively supported by electron-tab?

**Comment by Datta973** [comment]
Yes i was trying to mimic a new tab button,and (oops) i just realised that there is etabs-buttons (XP)..anyways "good job" on providing electron tabs,its really useful.
