### ISSUE TITLE
electron-tabs Not installing

### ISSUE THREAD

**Issue by Devhercule** [brrd/electron-tabs#28]
Hi, 

I want to use your example, it looks very interesting and i would like to test it.

1/ I downloaded it from git : git clone https://github.com/brrd/electron-tabs.git

2/ cd electron-tabs

3/ npm install --save electron-tabs

I have this result : 

D:\electron\electron-tabs>npm install --save electron-tabs
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "electron-tabs"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install electron-tabs as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\electron\electron-tabs\npm-debug.log

Can you help me fix it?

Thank you

**Comment by brrd** [comment]
By doing this you are actually trying to install electron-tabs as a dependency of itself, which is not possible.

Just do:

```
cd electron-tabs
npm install
```

Or if you want to use it in your project, use `npm install --save electron-tabs` but from your project directory (so you don't need to download it manually, npm will do it for you).

`npm install` documentation: https://docs.npmjs.com/cli/install

Someone also wrote a demo app for electron-tabs (I never tried it though): https://github.com/Vj3k0/electron-tabs

**Comment by Devhercule** [comment]
Thank you for your reply
I did what you said:

cd electron-tabs
npm install

and i have this as result : 

D:\electron\electron-tabs>npm install

D:\electron\electron-tabs>npm start
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\electron\electron-tabs\npm-debug.log

I can't test it

**Comment by brrd** [comment]
I don't really understand what you expect...
There is no demo yet in electron-tabs (see #6). For now you can use https://github.com/Vj3k0/electron-tabs or write your own demo app.

**Comment by Devhercule** [comment]
ahh ok thank you
I tested the example https://github.com/Vj3k0/electron-tabs it works
