### ISSUE TITLE
How do I add the attribute "partition" to Web Views inside the tab

### ISSUE THREAD

**Issue by shashankel** [brrd/electron-tabs#29]
I need to add the partition attribute to the web views in each tab. I tried the below. But it does not work.

const TabGroup = require("electron-tabs");

let tabGroup = new TabGroup();
let tab1 = tabGroup.addTab({
    title: "Tab - 1",
    src: "www.google.com",
    visible: true,
    webviewAttributes: "partition:tab1"
});

let tab2 = tabGroup.addTab({
    title: "Tab - 2",
    src: "www.bing.com",
    visible: true,
    webviewAttributes: "partition:tab2"
});

**Comment by brrd** [comment]
`webviewAttributes` is expected to be an object:

```javascript
webviewAttributes: {partition: "tab2"}
```

**Comment by shashankel** [comment]
Works. Thank you.
