### ISSUE TITLE
Declaring the electron-tabs so document is valid

### ISSUE THREAD

**Issue by ensiform** [brrd/electron-tabs#3]
I get the error regarding document being null on line 3 in your index.js before my app can actually be rendered when I have `const TabGroup = require('electron-tabs')` up by the rest of my const ... require lines.

But when I put it immediately after the main window is created it fails after window is drawn however still similar document not found error in a popup window.

```js
const path = require('path')
const electron = require('electron')

const BrowserWindow = electron.BrowserWindow
const app = electron.app

const debug = /--debug/.test(process.argv[2])

app.setName('Testapp')

var mainWindow = null

function initialize() {
    function createWindow() {
        var windowOptions = {
            width: 895,
            minWidth: 895,
            height: 560,
            title: app.getName()
        }

        if (process.platform === 'linux') {
            windowOptions.icon = path.join(__dirname, '/assets/app-icon/jack.png')
        }

        mainWindow = new BrowserWindow(windowOptions)
        mainWindow.loadURL(path.join('file://', __dirname, '/index.html'))
        mainWindow.setMenu(null)

        const TabGroup = require('electron-tabs')

        let tabGrid = new TabGroup()
        let genTab = tabGrid.addTab({
            title: "General",
            iconUrl: path.join('file://', __dirname, '/assets/icons/green%20vault%20symbol.png'),
            src: path.join('file://', __dirname, '/general.html'),
            visible: true
        });
        let charTab = tabGrid.addTab({
            title: "Character",
            iconUrl: path.join('file://', __dirname, '/assets/icons/red%20skull.png'),
            src: path.join('file://', __dirname, '/character.html'),
            visible: true
        });
        let vehTab = tabGrid.addTab({
            title: "Vehicle",
            iconUrl: path.join('file://', __dirname, '/assets/icons/wheel.png'),
            src: path.join('file://', __dirname, '/vehicle.html'),
            visible: true
        });
        let moneyTab = tabGrid.addTab({
            title: "Currency",
            iconUrl: path.join('file://', __dirname, '/assets/icons/pink%20seraph%20crystal.png'),
            src: path.join('file://', __dirname, '/currency.html'),
            visible: true
        });
        let travelTab = tabGrid.addTab({
            title: "Fast Travel",
            iconUrl: path.join('file://', __dirname, '/assets/icons/fast%20travel.png'),
            src: path.join('file://', __dirname, '/fasttravel.html'),
            visible: false
        });
        let backpackTab = tabGrid.addTab({
            title: "Backpack (0)",
            iconUrl: path.join('file://', __dirname, '/assets/icons/backpack.png'),
            src: path.join('file://', __dirname, '/backpack.html'),
            visible: true
        });
        let bankTab = tabGrid.addTab({
            title: "Bank (0)",
            iconUrl: path.join('file://', __dirname, '/assets/icons/bank.png'),
            src: path.join('file://', __dirname, '/bank.html'),
            visible: true
        });
        let rawTab = tabGrid.addTab({
            title: "Raw",
            iconUrl: path.join('file://', __dirname, '/assets/fugue/document-binary.png'),
            src: path.join('file://', __dirname, '/raw.html'),
            visible: true
        });
        let aboutTab = tabGrid.addTab({
            title: "About",
            iconUrl: path.join('file://', __dirname, '/assets/icons/question%20mark.png'),
            src: path.join('file://', __dirname, '/about.html'),
            visible: true
        });

        // Launch fullscreen with DevTools open, usage: npm run debug
        if (debug) {
            mainWindow.webContents.openDevTools()
            mainWindow.maximize()
            require('devtron').install()
        }

        mainWindow.on('closed', function () {
            mainWindow = null
        })
    }

    app.on('ready', function () {
        createWindow()
    })

    app.on('window-all-closed', function () {
        if (process.platform !== 'darwin') {
            app.quit()
        }
    })

    app.on('activate', function () {
        if (mainWindow === null) {
            createWindow()
        }
    })
}

initialize()
```

**Comment by brrd** [comment]
You are obviously using electron-tabs is the main process, which won't work.
electron-tabs is supposed to be called in the renderer process.

**Comment by ensiform** [comment]
There is no separate main-renderer process in any examples m8.  Thanks for no-help migrating it to renderer process. :-1:

**Comment by brrd** [comment]
> There is no separate main-renderer process in any examples m8.

You should read [the doc](https://github.com/brrd/electron-tabs/blob/master/README.md#usage) again where it explains that the module is supposed to be called in the renderer process. If something is not clear enough there then tell me what, so I would fix it, but please don't expect me to guess what you don't understand.

**Comment by ensiform** [comment]
Well perhaps explaining how to actually call the module in the renderer process would be helpful instead of making an assumption that it is widely common knowledge.  As is in the current version of Electron pre-built (1.x) it makes no distinction for the developer.  The type of "electron" in the above code is simply of type `Electron.ElectronMainAndRenderer` hence why it is extremely confusing for me.

**Comment by brrd** [comment]
Every script that you call in a window is running in the renderer process. Just add `<script src="renderer.js"></script>` in index.html head and call electron-tabs in renderer.js, as you would do for everything else related with the UI.

I'm not going to explain this in electron-tabs documentation because it is definitely a very common concept: http://electron.atom.io/docs/tutorial/quick-start/#renderer-process

You can also see an example here: https://github.com/electron/electron-quick-start/blob/master/index.html#L15

**Comment by ensiform** [comment]
Apologies, did not realize a script within the html file would function the same.  Thanks.

**Comment by KWLandry** [comment]
brrd commented on Jan 4, 2017  -  This comment is Extremely helpful, thank you, been at this for a couple of weeks and while I've read just about everything there is, including the quick start (as well as other quick starts) several times, and the main-renderer architecture discussion ,more than once, nowhere did I find anything that put that particular piece together, it's obviously obvious to a fair few but to the uninitiated it's not obvious and not getting there through reading the documentation, so, please keep that in mind. For those doing the pre-work, like reading docs and working examples, it's not always clear and the right note, as well as realizing the docs are missing that piece, and so updating docs to add that point, go a long way to cutting down on needless 'it doesn't work, why?' questions. 
So, Thanks for this, glad I stumbled on it, saving me hours, maybe weeks, 
KWL
