### ISSUE TITLE
open link in a new tab

### ISSUE THREAD

**Issue by Devhercule** [brrd/electron-tabs#36]
Hi,

I'm using your module electron-tabs to handle tabs il my Electron application.

I want to know how is it possible to open a new tab from an existing one. I want that the links existing in my webview can be opened in a new tab.

I added this coded in my referer.js :
 
```

const Menu = require('electron').remote.Menu;

document.querySelector('.etabs-views').addEventListener('contextmenu', (event) => {
	event.preventDefault();
	const template = [
		{
			label: 'open in a new tab,
			click: () => {
				let tab = tabGroup.addTab(function(){
					let tab = {
						title: 'new tab',
						src: 'http://www.example.com',
						visible: true,
						closable: true,
						active: true,
						ready: tab => {
							let webview = tab.webview;
						}
					};
					tabId++;
					return tab;
				});
			}
		}
	];
	const menu = remote.Menu.buildFromTemplate(template);
	menu.popup();
});
```
With this code, i can display the context menu when i click right, but I want to :

1/ display this menu only on clickable link

2/ open link in a new tab

Is it possible with your module?

Thank you

**Comment by leonliang33** [comment]
This is doable, I've done it by having event listener on the webview for 'new-window' and then I overwritten the default by adding a new tab to the tabgroup

**Comment by Devhercule** [comment]
Yes I confirm, i did it also with :

```
tab.webview.addEventListener('new-window', function (e) {
		addNewTab(e.url)
	});
```

Thanks any way
