### ISSUE TITLE
etabs-buttons location display

### ISSUE THREAD

**Issue by Devhercule** [brrd/electron-tabs#40]
Hi, 

I'm using electron-tabs to manages my tabs in Electron.

When I add many tabs and the tabs (in "etabs-tabs") return to line, the add button ("etabs-buttons") is placed in the third line instead of the second line.

Here is a screen shot:

![tabs](https://user-images.githubusercontent.com/29538843/30799030-d19250d0-a1db-11e7-8d71-562198d6fef5.PNG)

Can you tell me how to keep the "add button" ("etabs-buttons") on the left of the last added tab? and avoid returning to the line.

Thank you

**Comment by brrd** [comment]
> Can you tell me how to keep the "add button" ("etabs-buttons") on the left of the last added tab? and avoid returning to the line.

Right now this is not supported by the default CSS so you will have to write your own fix.
This will be added in a future release.

**Comment by Devhercule** [comment]
Ok thank you

Can you inform me when it's done?

**Comment by brrd** [comment]
> Can you inform me when it's done?

I'll close this issue so you will be notified if you receive github notifications.

**Comment by Devhercule** [comment]
Hi,

I would like to know if you have made the changes regarding my issue?

Thank you

**Comment by brrd** [comment]
Once again: if this thread is not updated then it means nobody worked on it. Please don't ask anymore.
By the way I currently don't have enough free time to work on electron-tabs. But contributions are welcome, so feel free to work on it if you want.
