### ISSUE TITLE
Webview not rendering after reload!

### ISSUE THREAD

**Issue by nguyenvuhuy** [brrd/electron-tabs#42]
I have the following code:

`$('document').ready(function () {
        $('#nav-refresh').click(function () {
            tabGroup.getActiveTab().webview.reload();
        })
    });`

When I click the refresh button, the site disappears, although I can still interact with the components in the site, I use the site https://demo.codeforgeek.com/notification/ as an example, I still click the "Show me notification" button even if it's a blank page. Thank you!

Video description:
https://youtu.be/o9YQyirasGE

**Comment by brrd** [comment]
I looks like an issue with Electron webview. `webview.reload()` method is part of Electron API. You should check Electron issues: https://github.com/electron/electron/issues

**Comment by nguyenvuhuy** [comment]
Thank you for your feedback!

You are right, this problem belongs to the Electron API, I found it at https://github.com/electron/electron/issues/6139, it involved enable GPU acceleration on Linux, I added the line of code :
`if (process.platform === 'linux') {
app.disableHardwareAcceleration ();
}
`
Although this is a bad thing related to the performance of the application.It seems that on linux, the driver for hardware is always a difficult issue :)))
