### ISSUE TITLE
Not allowing onclick actions

### ISSUE THREAD

**Issue by ECDonelson** [brrd/electron-tabs#49]
I'm cant call an internal function that I've written while using electron-tabs.

I would like to use the tab functionality but create my own "views" so to speak.

I have the views populating with the static data I want (used for a demo at the moment) but I cant seem to be able to submit anything from a button click.

**Comment by ECDonelson** [comment]
It'd also be great to be able to target DOM content also

**Comment by brrd** [comment]
I don't understand your issue. Please describe what you want to do, what you actually get, and give a sample of your code.

**Comment by ECDonelson** [comment]
I cant target a buttons "onclick" event. I also cant see my DOM content when using electron-tabs.

![image](https://user-images.githubusercontent.com/34381278/36265225-675327ca-1234-11e8-8bfa-e10fa8e39fde.png)

That's the html, I have the javascript loaded the way it should be, but I cant get to this function:

![image](https://user-images.githubusercontent.com/34381278/36265266-78ae2a06-1234-11e8-9804-ea6a24837640.png)

But I cant see anything in the dev tools other than the webview's

![image](https://user-images.githubusercontent.com/34381278/36265474-e0658432-1234-11e8-892f-2d7697ad3cba.png)

So, why is it that I can call the function in dev tools implicitly, but cant from an onclick event using electron tabs? I can do this in another program without electron tabs, but I'd like to be able to serve the user tabs (from html that I've written) instead of some html from some other site.

**Comment by brrd** [comment]
I'm sorry I don't understand what you are trying to do. 
Maybe you should provide a full example in a separate repo.

**Comment by ECDonelson** [comment]
I'm trying to submit a form based on a button click using electron tabs but I cant see the button in the dev tools and when I click the button it doesnt go to the function I've given it for the onclick event.

**Comment by brrd** [comment]
Then you have to open a new devtool instance connected to the tab's webview with `tab.webview.openDevTools()`.
See webview documentation: https://www.electronjs.org/docs/api/webview-tag#webviewopendevtools
