### ISSUE TITLE
tabs bottom

### ISSUE THREAD

**Issue by stef-pellegrino** [brrd/electron-tabs#5]
Hi,
Is there a way to set tabs on top or bottom ?
By default, the tabs are settings at the bottom of the page

**Comment by brrd** [comment]
This is determined by the markup of your page and your CSS.

>  By default, the tabs are settings at the bottom of the page

Normally if you follow the readme tabs will be displayed at the top.
If you want them to be displayed at the bottom, just move .etabs-views before .etabs-tabgroup (you will maybe have to adjust some details in the CSS).
