### ISSUE TITLE
Script tag contents not running

### ISSUE THREAD

**Issue by LightningBladeXYZ** [brrd/electron-tabs#51]
I currently am using the files from the demo but have adapted them slightly to instead of pointing to google in the first tab, make it point to a local file instead and set it as the active and visible tab. However, the code in the script tags aren't executing. Would I have to run those via ipc then, or is there something which I don't seem to be able to understand about how this loads the webpages?

The contents of the loaded html file are as follows:

```<!DOCTYPE html>
  <html>
    <head>
      <meta charset="UTF-8">
    </head>
    <body>
      <h1>Hello World!</h1>
      We are using node <script>document.write(process.versions.node)</script>,
      Chrome <script>document.write(process.versions.chrome)</script>,
      and Electron <script>document.write(process.versions.electron)</script>.
    </body>
  </html>

**Comment by brrd** [comment]
Sorry for the late reply, I lacked time to investigate 😕 

By default node integration is disabled in webviews (see https://electronjs.org/docs/api/webview-tag#nodeintegration), so `process` is `undefined`.

Setting `nodeintegration: true` in `webviewAttributes` should solve your issue:

```javascript
tabGroup.addTab({
  title: "Test",
  src: "./test.html",
  webviewAttributes: {
    nodeintegration: true
  }
});
