### ISSUE TITLE
Prevent Tab close is loaded webview prevent unload

### ISSUE THREAD

**Issue by MCMicS** [brrd/electron-tabs#53]
If you load a website with onbeforeevent to prevent reload the tab will still close without any hint.

It would be nice if the close will respect the unload event.

BTW: It is possible to cancel the closing from within 'closing' event?

**Comment by chs09** [comment]
@brrd: I have a similar problem. You can enable custom close handlers by replacing the following code in the `initTabButtons` function (around line 374):
```javascript
button.addEventListener("click ", this.close.bind (this, false), false);
```
should be replaced by:
```javascript
button.addEventListener ("click", function () {this.close.apply (this, arguments)} .bind (this, false), false);
```


With this the user could override `tab.close ()`. e.g .:
```javascript
let orgClose = tab.close;
tab.close = (force) => {
    if (force) {
        orgClose ();
        return;
    }

    tab.webview.executeJavaScript ('(typeof window.onbeforeunload === "function")?window.onbeforeunload (): true;', (result) => {
        alert (result);
    })
};
```

**Comment by brrd** [comment]
@chs09 Actually, listening for the unload event as suggested by @MCMicS sounds more recommended to me. Such events are standardized, and overriding lib methods as you say looks like a very bad idea IMHO since it can cause unpredictable behaviors when upgrading.

**Comment by LiamBest** [comment]
> BTW: It is possible to cancel the closing from within 'closing' event?

@MCMicS not sure if you already solved this but you can do something like this to stop a tab closing:
`tab.on("closing", function(tab) { tab.closable = confirm('Are you sure you wish to close this tab?'); });`

**Comment by brrd** [comment]
In electron-tabs 0.14 you can now cancel the closing event by doing:

```javascript
tab.on("closing", (tab, abort) => { 
  abort();
});
```

You will probably also have to work with [webContents 'will-prevent-unload' event](https://www.electronjs.org/docs/api/web-contents#event-will-prevent-unload) in order to intercept the unload event. I didn't add this part into electron-tabs because it is too specific IMO.

**Comment by MCMicS** [comment]
Thanks for fixing
