### ISSUE TITLE
Isolating Cookies

### ISSUE THREAD

**Issue by rvrn22** [brrd/electron-tabs#57]
Hi,

Is there a way to isolate cookies between the tabs ?
Like I would like to open 2 different Gmail tabs, for 2 different account.

Thanks

**Comment by brrd** [comment]
Try with the `session` module: https://electronjs.org/docs/api/session

You can access Electron's webview element with : 
```javascript
let webview = tab.webview;
```

Also related: https://github.com/electron/electron/issues/959
