### ISSUE TITLE
Attempting to close all tabs currently open.

### ISSUE THREAD

**Issue by trentis** [brrd/electron-tabs#58]
![image](https://user-images.githubusercontent.com/13172339/43372932-83843f92-93e9-11e8-90d0-0305a3e96580.png)

Just trying to build a context menu for the tab group so I can right click tabs etc. The issue I'm having is some of the functions don't seem to fully run. Seems to only close a random amount of tabs that are currently open. I don't know if it is a timing issue or something else.

I am assuming this might be asking for a bit much but I think Close, Close Others and Close All would be good use cases for other functions an example being VScode or Atom Tabs. 

Just realised this line in close causes the delay so maybe you know whats up?

`        TabGroupPrivate.removeTab.bind(tabGroup)(this, true);`

**Comment by brrd** [comment]
Is there any message in the console?

**Comment by trentis** [comment]
The each tab function loops through fine goes through them all when I log the output. But when I attempt to close a tab while logging only 2-3 tabs will log to console. 

I won't have access to the computer till tomorrow. But feel free to tell me anything I can do to help debug and I'll try it tomorrow. Sorry just on the mobile right now figured I'd respond with at least some information

Thanks Trent

**Comment by trentis** [comment]
Seems to have solved my issue.  You can resolve this as not a bug. But from reading the documentation I feel like the tabgroup.eachtab should still be looping through it even though the array may change?

Thanks

Trent

**Comment by maxosprojects** [comment]
There are not that many operations that leave that collections intact, so it is a bug in the `eachTab()` method. Created a [PR](https://github.com/brrd/electron-tabs/pull/65) to fix that.
