### ISSUE TITLE
Separate local storages for separate tabs possible?

### ISSUE THREAD

**Issue by ShadyThGod** [brrd/electron-tabs#68]
I want to create separate instances of WhatsApp Web in the same apps as tabs, but since the tabs share the same local storage, I am not able to create separate WhatsApp instances. So, is it possible to have separate local storages for separate tabs or maybe some kind of workaround?

**Comment by brrd** [comment]
I think this is related to #57.

See: 

* https://electronjs.org/docs/api/webview-tag#partition
* https://github.com/electron/electron/issues/959

I would try something like:

```javascript
tabGroup.addTab({
  webviewAttributes: {
    partition: "foo"
  }
});

tabGroup.addTab({
  webviewAttributes: {
    partition: "bar"
  }
});
```

**Comment by ShadyThGod** [comment]
Thank you very much. That did it.
