### ISSUE TITLE
CSS conflict

### ISSUE THREAD

**Issue by stef-pellegrino** [brrd/electron-tabs#7]
Hi,
bootstrap.css  is conflicting with  the property "box-sizing" of etabs.
So, the render of .etabs-tabs borders is not correct.

**Comment by brrd** [comment]
@stef-pellegrino Could you provide a sample app or a screenshot?

**Comment by nitish173** [comment]
Should't this issue be closed for the lack of response from the opener of the issue? Looks too old, maybe irrelevant now? @brrd ?
