### ISSUE TITLE
Webview not focusing until tab is clicked

### ISSUE THREAD

**Issue by ppeterson104** [brrd/electron-tabs#71]
Ever since I upgraded to Electron 3+ (which incidentally upgraded Chromium), webview has been working oddly when loading in the tabs.  Essentially, the tab and the html appears to render with the css, but, certain things are not loading, such as highlight effects when clicking in the inputs, and the cursor does not show up.  If I click on the tab, the page then functions as normal.  It's a minor issue, and definitely not a deal breaker, but, I imagine this was some kind of change in the Chromium webview behavior. Oddly enough, if I open a dev tools window, focus is correctly applied to the webview.

**Comment by ramzimaalej** [comment]
this might solve your problem: it's a known issue in Electron

`  tab.webview.addEventListener("dom-ready", event => {
        // Remove this once https://github.com/electron/electron/issues/14474 is fixed
        tab.webview.blur();
        tab.webview.focus();
    });`
