### ISSUE TITLE
Tab Title dont change automaticly

### ISSUE THREAD

**Issue by thombien** [brrd/electron-tabs#73]
When I navigate, i cant set tab title as web page title element

**Comment by brrd** [comment]
This feature is not planned because mimicking browser behavior is not the goal of electron-tabs. You will have to write your own solution based on webview events and methods.

I would try this:

```javascript
const webview = tab.webview;
webview.addEventListener('page-title-updated', () => {
  const newTitle = webview.getTitle();
  tab.setTitle(newTitle);
});
```
