### ISSUE TITLE
electron-tabs doesn't work with electron 5.0.0.

### ISSUE THREAD

**Issue by Tommy-LSA** [brrd/electron-tabs#76]
To Reproduce:
Create a new folder
```
npm init
npm install electron (installs the latest automatically)
npm install electron-tabs
cd node_modules/electron-tabs
npm run demo
```

Result: Window opens but no tabs loaded

webPreferences: {nodeIntegration: true} for browser window in app.js doesn't help.

Workaround:
downgrade to "electron": "4.2.2"

**Comment by brrd** [comment]
I guess you are talking about the demo and this doesn't apply to the lib itself?

**Comment by brrd** [comment]
If so, the demo is actually supposed to be installed from electron-tabs package and uses electron 1.6: https://github.com/brrd/electron-tabs/blob/master/package.json#L23

```
git clone https://github.com/brrd/electron-tabs.git
cd electron-tabs
npm init
npm run demo
```

**Comment by Tommy-LSA** [comment]
I tested it on an own Application and only use the demo as example to illustrate the issue for this issue. You also can write an own Application, using electron 5 and try getting electron-tabs running and will see it won‘t work. I havn‘t seen a limitation in readme to use electron versions below 5.

**Comment by brrd** [comment]
OK. Mention to app.js in your initial message actually misled me.

> I havn‘t seen a limitation in readme to use electron versions below 5.

I currently lack time to maintain this module, but contributions are welcome.

**Comment by Tommy-LSA** [comment]
No worries, I have no need to use electron 5 actually. But better having noted that, to save other people from endless searching for a bug in their own code on a known issue. I wasted a few hours on my code until I got the idea to downgrade electron. From this moment everything worked as expected.

**Comment by brrd** [comment]
I pinned this issue to highlight it until it is fixed.

**Comment by zhouyangit** [comment]
You now need to explicitly enable webviewTag in your webPreferences object.
```
const mainWindow = new BrowserWindow({
  webPreferences: {
    webviewTag: true
  }
})
```

**Comment by kanryu** [comment]
My project is running electron@6.0.10, but this issue has not been solved.
![スクリーンショット 2019-09-21 22 53 11](https://user-images.githubusercontent.com/759165/65374231-8c78bd80-dcc2-11e9-8a1e-c1a55ad77f74.png)
