### ISSUE TITLE
Use Angular router link in new tab src tag in an Electron app

### ISSUE THREAD

**Issue by MohammadAhadi** [brrd/electron-tabs#77]
i have project with angular and electron. using electron-tabs.
how to using route for load component page in tabs.

**Comment by MohammadAhadi** [comment]
I am using electron with angular 7. Trying to open each router link as a new tab but I am not finding anything that could help me to achieve this. Here is a piece of code for creating a new tab in electron:

  newtab(str: string) {
    let tab = this.tabGroup.addTab({
      title: str,
      src: 'Here I want to use Router link',
      visible: true,
      active: true,
      iconURL: '',
How can I insert a router link in src tag?

**Comment by MY020537** [comment]
@MohammadAhadi  - Were you able to accomplish this ? i am also looking to load some angular route in electron-tabs ?

**Comment by aayusharora** [comment]
Hi @MohammadAhadi @MY020537 
Have you guys found a solution?
