### ISSUE TITLE
Avoiding Creating Tabs in a new line and making all of them in one line

### ISSUE THREAD

**Issue by MohammadAhadi** [brrd/electron-tabs#78]
how to create button next and before for move in tab in tabGroup?

**Comment by brrd** [comment]
I don't understand. What are you trying to do exactly?

**Comment by MohammadAhadi** [comment]
When I create a lots of tabs, if in screen there is no place to showing all, then the new tabs will be created in the next line. I want to avoid such behavior.  I need if the tabs count is not fit to the screen then user can scroll horizontally to see new ones or he can use click on a next button to view tabs which is now outside of screen. somethings like notepad++ when you create so many tabs.

![CaptureF](https://user-images.githubusercontent.com/46159653/62123834-0a7da100-b2de-11e9-8967-93a8fed01171.JPG)

**Comment by brrd** [comment]
Duplicate #50.
