### ISSUE TITLE
insertCss

### ISSUE THREAD

**Issue by DaCardinal** [brrd/electron-tabs#8]
Is it possible to call the insertCSS function of electron webView();? if so how do I do that? I tried 

```
tab = tabGroup.addTab({
        title: 'Electron',
        src: path.join(appBase, '/views/main-frame/index.html')
        visible: true,
        active: true,
        webviewAttributes: {
          nodeintegration: true,
          plugins: true
        },
        ready: function (tab) {
          tab.webview.insertCSS("background-color:red;");
        }
    });
```

**Comment by brrd** [comment]
Actually `ready(arg)` argument is not a tab but a tabGroup, so this should work better:

```javascript
ready: function (tabGroup) {
	var tab = tabGroup.getActiveTab();
	tab.webview.insertCSS("background-color:red;");
}
```

**Comment by DaCardinal** [comment]
Got this error:

 ```
Uncaught TypeError: tabGroup.getActiveTab is not a function
 at Object.ready
at new Tab
at TabGroup.addTab
at initTabs
 at HTMLDocument.document.onreadystatechange
```

**Comment by brrd** [comment]
Sorry, this is my mistake! Please forget my previous post. Actually you were totally right with your first code, but as it's specified in electron documentation ([here](http://electron.atom.io/docs/api/webview-tag/#methods)): 

> The webview element must be loaded before using the methods.

So you must wait for the webview to be loaded before using `insertCSS`.

Another mistake is the parameter you use in `insertCSS`. It is supposed to be a valid CSS rule with a selector.

So this code should work finaly:

```javascript
tab = tabGroup.addTab({
        title: 'Electron',
        src: path.join(appBase, '/views/main-frame/index.html')
        visible: true,
        active: true,
        webviewAttributes: {
          nodeintegration: true,
          plugins: true
        },
        ready: function (tab) {
	  var webview = tab.webview;
	  webview.addEventListener('did-finish-load', function () {
	    webview.insertCSS("body{ background-color: red;}");
	  });
        }
    });
```

Hope this helps.

**Comment by brrd** [comment]
By the way, I just wrote feature request #9 which can help to handle this in a more convenient way.

**Comment by DaCardinal** [comment]
Thanks! This was really useful. Good job with the plugin as well.
