### ISSUE TITLE
ReferenceError after creating a tab

### ISSUE THREAD

**Issue by millimoose** [brrd/electron-tabs#95]
**Describe the bug**
Exception when loading any window using tabs:

```
Uncaught ReferenceError: tab is not defined
    at HTMLElement.<anonymous> (index.js:408)
    at WebViewImpl.dispatchEvent (web-view-impl.ts:125)
    at dispatchEvent (guest-view-internal.ts:59)
    at EventEmitter.<anonymous> (guest-view-internal.ts:77)
    at EventEmitter.emit (events.js:210)
    at Object.onMessage (init.ts:50)
```

Given it's in a DOMReady event handler, it doesn't really do much damage.

**To Reproduce**

Just create any `Tab` object through `addTab()`.

**Expected behavior**

The exception not to happen, and the intended workaround for the Electron bug that code accomplishes to work.

**Please complete the following information**
 - OS: Windows 10
 - electron-tabs v0.12.0
 - Electron v8.0.0

**Additional information**

The exception comes from the following source code: https://github.com/brrd/electron-tabs/blob/30c466692124cbe145c94016d0144eb05f185bd9/index.js#L408-L409

Near as I can tell there is no variable `tab` in scope, probably should be `this.tab` as in the rest of the code above.

**Comment by brrd** [comment]
Yes, definitely. I will fix this. 
Thank you very much for this very clear description.
