### ISSUE TITLE
JS code for tabs bypasses VSCode Problems report

### ISSUE THREAD

**Issue by kakyoism** [brrd/electron-tabs#98]
**Before posting your issue, please make sure it is not related to Electron or the `<webview>` tag by checking Electron issues (https://github.com/electron/electron/issues).**

**Describe the bug**
JS syntax errors in a tab JS source file is not caught by VSCode and causes electron app to break, without any interpreter feedback.

**To Reproduce**
Using the the following renderer.js and the tab code where there is a syntax error,
upon running this code from VSCode, 

- no error will be reported under Problems.
- no issues will be reported under Chromium debug console, either.

**Expected behavior**

The syntax error should receive feedback from either VSCode or Electron's Chromium debugger.

**Please complete the following information**
 - OS: [macOS 10.15]
 - Browser [Chrome]
 - electron-tabs version [0.11.0]
 - Electron version [7.1.9]

**Code**

My renderer.js

```js
const { remote, ipcRenderer } = require('electron');
const TabGroup = require("electron-tabs");
const mainProc = remote.require('./main.js'); // plug in main process
const parser = new DOMParser();

let tabGroup = new TabGroup({
    newTab: {
        title: 'New Tab'
    }
});

tabGroup.addTab({
    title: 'Google',
    src: './tab1.html',
    closable: false,
    active: true,  // tab button is foregrounded
    webviewAttributes: {
        nodeIntegration: true,
        webviewTag: true
    }
});

tabGroup.addTab({
    title: "Electron",
    src: './tab2.html',
    closable: false,
    // visible: true,
    webviewAttributes: {
        nodeIntegration: true,
        webviewTag: true
    }
});
```

The tab HTML: `tab1.html`:

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="
        default-src 'self' 'unsafe-inline';
        script-src 'self' 'unsafe-inline';
        connect-src *">
        <!-- <meta http-equiv="Content-Security-Policy" content="default-src * self blob: data: gap:; style-src * self 'unsafe-inline' blob: data: gap:; script-src * 'self' 'unsafe-eval' 'unsafe-inline' blob: data: gap:; object-src * 'self' blob: data: gap:; img-src * self 'unsafe-inline' blob: data: gap:; connect-src self * 'unsafe-inline' blob: data: gap:; frame-src * self blob: data: gap:;"> -->
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Bookmarker</title>
    <link rel="stylesheet" href="style.css" type="text/css">
    <script type="text/javascript" src="tab1.js" defer></script>
</head>

<!-- <body>
    <h1>Hello from Electron</h1>
</body>
<p>
    <button class="alert">Current Directory</button>
</p> -->
<h1>Bookmarker</h1>
<div class="error-message"></div>
<section class="addnewlink">
    <form class="new-link-form">
        <input type="url" class="new-link-url" placeholder="URL" size="100" required>
        <input type="submit" class="new-link-submit" value="Submit">
    </form>
</section>
<section class="links"></section>
<section class="controls">
    <button class="clear-storage">Clear Storage</button>
</section>

</html>
```

The JS code for the tab: `tab1.js`

```js
class My {
    constructor() {
        alert('My class');
    }
}

var my = My(); // syntax error: missing "new" keyword
```

Here is my launch.json for VSCode Electron debugger

```json
{
  "version": "0.2.0",
  "configurations": [
      {
          "type": "node",
          "request": "launch",
          "name": "Launch Electron against the workspace",
          "program": "${workspaceFolder}/app/main.js",
          "stopOnEntry": false,
          "args": [],
          "cwd": "${workspaceRoot}",
          "preLaunchTask": null,
          "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
          "runtimeArgs": [
              "${workspaceRoot}",
              "--enable-logging",
              "--nolazy",
              "--require",
              "babel-register"
          ],
          "env": {},
          "console": "internalConsole",
          "sourceMaps": true,
          "outFiles": []
      },
      {
          "name": "Attach",
          "type": "node",
          "request": "attach",
          "port": 5858,
          "address": "localhost",
          "restart": false,
          "sourceMaps": false,
          "outFiles": [],
          "localRoot": "${workspaceRoot}",
          "remoteRoot": null
      },
      {
        "name": "Attach to Process",
        "type": "node",
        "request": "attach",
        "processId": "${command:PickProcess}",
        "port": 5858,
        "sourceMaps": false,
        "outFiles": []
    }
  ]
}
```

**Additional information**

Syntax errors in `main.js` and `renderer.js` are caught by VSCode or the Chromium debugger, as expected. It's just that the tab code seems to be out of sight of the IDE and Chromium dev tools.

**Comment by kakyoism** [comment]
I found a workaround. But I'd like to confirm that what I did is the correct solution, not a hack.

To my understanding, with Electron, we need to **include ALL scripts into the relevant processes**, e.g., main or renderer, to be able to use the debug consoles. Otherwise, no feedback will be available except for the basic linter that VSCode comes with.

After adding the offending scripts to my main HTML, so that it looks like:

```html
    <script>
        // You can also require other files to run in this process
        require('./renderer.js')
        require('./tab1.js')
    </script>
```

the debug console starts working on these additional scripts such as `tab1.js`.

But does it mean that I'd have to include all scripts to these two processes only?

**Comment by brrd** [comment]
This is an issue with VSCode, not with electron-tabs. We don't know VSCode enough to answer. 
Please ask this question in VSCode issue tracker, where you are more likely to have a useful answer

**Comment by kakyoism** [comment]
> This is an issue with VSCode, not with electron-tabs. We don't know VSCode enough to answer.
> Please ask this question in VSCode issue tracker, where you are more likely to have a useful answer

Actually, after requiring the tab code, I start seeing things in Electron's chrome devTools, not VSCode.
